// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clbkzuqzoxlpuvbkybli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsYmt6dXF6b3hscHV2Ymt5YmxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MjkwOTIsImV4cCI6MjA3NDIwNTA5Mn0.EJYnXX3abi2wG8D3H3xdcT8yMEV4RwHihGSONSkSYF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});